version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8002:80"
    depends_on:
      - auth-api
      - todos-api
      - users-api

  auth-api:
    build: ./auth-api
    ports:
      - "8085:8080"

  todos-api:
    build: ./todos-api
    ports:
      - "3001:3000"
  users-api:
    build: ./users-api
    ports:
      - "8081:8081"

  log-processor:
    build: ./log-processor
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
